# Generated by Django 4.0.2 on 2022-03-24 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=256)),
                ('PatientCondition', models.CharField(max_length=256)),
                ('PatientClinician', models.CharField(max_length=256)),
                ('PatientClinicianEmail', models.CharField(max_length=256)),
                ('DateOfLastVisit', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('PatientAdmitDate', models.DateField(default=django.utils.timezone.now)),
                ('PatientReleaseDate', models.DateField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(default=django.utils.timezone.now, help_text='Time is in GMT')),
                ('UpdatedOn', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('IsActive', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
            ],
            options={
                'verbose_name': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhysicianName', models.CharField(max_length=256)),
                ('ListOfPatients', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Physician',
            },
        ),
        migrations.CreateModel(
            name='UpcomingAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=256)),
                ('PhysicianName', models.CharField(max_length=256)),
                ('DateOfAppointment', models.DateField()),
                ('Time', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Upcoming Appointment',
            },
        ),
    ]
