# Generated by Django 4.0.2 on 2022-03-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='AppointmentOverdue',
            field=models.IntegerField(blank=True, choices=[(1, 'Overdue'), (0, 'Fine')], default=0, help_text='1 -> Overdue, 0 -> Fine', null=True),
        ),
    ]
