# Generated by Django 4.0.2 on 2022-02-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare_api', '0002_alter_patient_options_patient_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='created_on',
            new_name='CreatedOn',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='is_active',
            new_name='IsActive',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='updated_on',
            new_name='UpdatedOn',
        ),
    ]
