# Generated by Django 4.0.2 on 2022-04-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare_api', '0004_physician_physicianemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='RegulationZone',
            field=models.IntegerField(blank=True, choices=[(0, 'Green'), (1, 'Blue'), (2, 'Yellow'), (3, 'Red')], default=0, null=True),
        ),
    ]
