# Generated by Django 4.0.2 on 2022-04-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare_api', '0005_patient_regulationzone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='RegulationZone',
            new_name='status',
        ),
    ]
