# Generated by Django 4.0.2 on 2022-04-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare_api', '0011_alter_patient_regulationzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='RegulationZone',
            field=models.CharField(blank=True, choices=[('Green', 'Green'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Red', 'Red')], default='Green', max_length=256, null=True),
        ),
    ]
